export * from './grammar/roles.js';
export type * from './grammar/types.js';
export { motionFor } from './grammar/motion.js';
export type { MotionSpec } from './grammar/motion.js';
export { validateProfile, validateMapping } from './grammar/profiles.js';
export { validateSnapshot, projectState, announcementChanged } from './grammar/validate.js';
export { default as ForgeProcessGlyph } from './components/ForgeProcessGlyph.svelte';
export { default as ForgeStatusCapsule } from './components/ForgeStatusCapsule.svelte';
export { default as ForgeEvidenceSeal } from './components/ForgeEvidenceSeal.svelte';
export { default as ForgeAuthorityGate } from './components/ForgeAuthorityGate.svelte';
export { projectHud } from './adapters/hud.js';
export type { HudInput, HudPresentation, HudAction } from './adapters/hud.js';
export { default as ForgeHudFooter } from './components/ForgeHudFooter.svelte';
export { default as ForgeHudRail } from './components/ForgeHudRail.svelte';
export { default as ForgeLockIndicator } from './components/ForgeLockIndicator.svelte';
export { default as ForgeNextAction } from './components/ForgeNextAction.svelte';

export { default as ForgeBackendActivity } from './components/ForgeBackendActivity.svelte';
export { activityState, PROVIDERS } from './adapters/activity.js';
export type { BackendActivity, ProviderId } from './adapters/activity.js';
export { ACTIVITY_PHASES, parseObservation, acceptObservation, observationKey, projectObservation } from './adapters/observations.js';
export type { ActivityScope, ActivityPhase, ActivityObservation } from './adapters/observations.js';
